

GET http://0.0.0.0:8000/user/myAccount HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInNlcnZlcl9pZCI6MSwiaWF0IjoxNzAzNDE4MTc5LCJleHAiOjE3MDM0MjcxNzl9.Vn4nsjYrSREXXQj2p7pVE6boPcEnVAKBmMlrP3JvSE8



###


PATCH  http://0.0.0.0:8000/user/updatePassword HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInNlcnZlcl9pZCI6MSwiaWF0IjoxNzAzNDE4MDQ0LCJleHAiOjE3MDM0MjcwNDR9.1ND-E-ce_2092snU7c8j8LdY7OhDiknazfAy5Yitw08
Content-Type: application/json

{
    "newPassword": "12321321"
}



###  For admins

POST   http://0.0.0.0:8000/user/createUser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInNlcnZlcl9pZCI6MSwiaWF0IjoxNzAzNDE4MDQ0LCJleHAiOjE3MDM0MjcwNDR9.1ND-E-ce_2092snU7c8j8LdY7OhDiknazfAy5Yitw08
Content-Type: application/json

{
    "username": "sedef-1",
    "password": "123"
}


